all:	
	gcc -c medusa.c -o libmedusa.so -I"/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6/" -I"/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/include"

clean:
	rm medusa.o